### ISSUE TITLE
Link this repo to main

### ISSUE THREAD

**Issue by Axemasta** [commandlineparser/commandline_sampleapp#1]
The documentation & samples on the main CommandLineParser project are confusing at best. The examples given in this repo are very clear and easy to implement.  I would suggest adding this to the demo section of the main repository as it was not apparent that this repo existed at all!

**Comment by nemec** [comment]
The samples in this project were copy-pasted from [this section of the readme](https://github.com/commandlineparser/commandline#quick-start-examples) - if you compare the two, they are the exact same. I suppose it wouldn't hurt to link to this repo anyway, though.
